### ISSUE TITLE
Undefined Icon Titles in Dialog

### ISSUE THREAD

**Issue by mrezakootvaal** [josh18/TinyMCE-FontAwesome-Plugin#10]
Hi,
-Titles of Icons not showing in Dialog box and it show "Undefined" text, please check this problem
Thanks.

![undefined_fontawesome_for_tinymce](https://cloud.githubusercontent.com/assets/12181520/7444484/4beaea76-f19a-11e4-8229-5c7d96ad3037.JPG)

**Comment by josh18** [comment]
Most likely something to do with the language files. What language (if any) do you have set?

**Comment by mrezakootvaal** [comment]
I work with default language of the TinyMCE editor (English file), and also in "fa_IR" language it showed like this

**Comment by cliffparnitzky** [comment]
Seems to be a probleme with getting the language via `lang[...]`. I've made PR #11 which solves the probleme in my environment.

**Comment by mrezakootvaal** [comment]
@cliffparnitzky Yeah sounds like good, it is working with your solution ;)  Thanks you so much

**Comment by cliffparnitzky** [comment]
:+1:

**Comment by josh18** [comment]
Sorry just looking at this now. I am using TinyMCE v4.0.5 so I wonder if that's why it is working for me and not you guys. Gonna upgrade to the latest version (4.1.10) and see what happens.

**Comment by josh18** [comment]
Yeah they must have changed something in TinyMCE. Fixed now: 727a83d4fc6cf922cfaf119f00af2658fdc3dcab

**Comment by cliffparnitzky** [comment]
great, thank you
