### ISSUE TITLE
Select size?

### ISSUE THREAD

**Issue by Bokkeman** [josh18/TinyMCE-FontAwesome-Plugin#16]
Hi could you add a dropdown in your dialog so the user can pick the size class of the injected FA span? i.e. fa-2x, etc. My users are too dumb to edit the TinyMCE source
I tried to create a pull request but unfortunately I don't have time to master the intricacies of MCE dialog markup ...

**Comment by josh18** [comment]
I can see how this could be useful but I don't think I'll add it in, sorry. In my case I don't want users to be changing font size (or icon size) as it often messes up the design. Instead I think it's better if the icon inherits the current font size.
