### ISSUE TITLE
Some icons are not shown in the Icons menu (Tinymce)

### ISSUE THREAD

**Issue by Liewebs** [josh18/TinyMCE-FontAwesome-Plugin#18]
Hi,

I have installed your plugin in the tinymce for Prestashop 1.6.1.1 but in the icons menu to select icons, there is some icons that don't show correctly. Please check attachment.

Thanks!
![post-888037-0-24928600-1442220822](https://cloud.githubusercontent.com/assets/14276490/9851883/89afac00-5afb-11e5-8f7b-c408f22b3d67.png)

**Comment by josh18** [comment]
Sorry I forgot about this, are you still having this issue? It is most likely due to an older version of Font Awesome being used.

**Comment by Liewebs** [comment]
Yes, I still have this issue. Can you fix it?

2015-09-27 21:54 GMT+02:00 Josh <notifications@github.com>:

**Comment by josh18** [comment]
It's not an issue with this plugin, as I said you probably have an older version of Font Awesome running. Do you have this line?
```
content_css: '//netdna.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css';
```

**Comment by Liewebs** [comment]
Yes, I have this line configured in tinymce.inc.js fil as you said in the
instructions.

2015-09-27 23:10 GMT+02:00 Josh <notifications@github.com>:

**Comment by josh18** [comment]
Definitely says "4.4.0"? Otherwise I'm not sure what's going on, seems to be working for me though.

**Comment by Liewebs** [comment]
yes. 4.4.0. Another person reports me the same issue. we are two with same
issue. Do you have it in Tinymce Prestashop editor or another?

2015-09-27 23:20 GMT+02:00 Josh <notifications@github.com>:

**Comment by Liewebs** [comment]
It happens only in the fontawesome menu. If I add to the text area an icon hidden by this issue, in the text area It works ok.

**Comment by Liewebs** [comment]
My tiny mce is 4.0.16 version modifed by Prestashop developers. the version of tinymce installed in last
Prestashop version 1.6.1.1. Please can you check it in a local server?

**Comment by josh18** [comment]
I'm just using it with TinyMCE and it is working fine for me. Almost certainly an issue with FontAwesome versions as you can see that it's all the [icons from 4.4](http://fontawesome.io/icons/) that are missing. Maybe something else is loading in a previous version of FontAwesome? Have you got a demo that I can look at?

**Comment by Liewebs** [comment]
Hi, I don't have a demo. Only my shop under production and actived. I can
send you a video demo if you want.

2015-09-28 1:54 GMT+02:00 Josh <notifications@github.com>:

**Comment by josh18** [comment]
I had a look at [this demo](http://demo.prestashop.com/en/?view=back) and as you can see by the screenshot PrestaShop is loading in FontAwesome v4.3.0 instead of v4.4.0 which is overriding the font that my plugin is loading in.

I don't use PrestaShop though so I can't help you fix it. Maybe you can find the font files that PrestaShop loads in and update them to the latest version of FontAwesome? Or ask PrestaShop to upgrade to the latest version of FontAwesome?

![screenshot](https://cloud.githubusercontent.com/assets/5900962/10176488/8547c23a-6751-11e5-8322-07f48adb3c2a.png)

**Comment by Liewebs** [comment]
My website charge the correct version of Fontawesome. I just checked.
![fontawesome](https://cloud.githubusercontent.com/assets/14276490/10176813/34143d4e-66f7-11e5-9009-216a22031b1a.jpg)

for that, I don't know what is the reason of this problem. I will continue figure out the origin of this problem...

**Comment by josh18** [comment]
Hmm that's probably the version that my plugin loads in as you can see it is from netdna.bootstrapcdn.com. From the demo that I was looking at earlier it looks like PrestaShop loads it in from `themes/default/fonts`? Can you run a search on all your code for "4.3.0"?

**Comment by Liewebs** [comment]
Hi,

I have changed the link to 4.3.0 but the problem is still. I think the
problem is in some css file from your plugin. Because It is only in the
icons menu. When I add an icon, this icon is OK. But in the icons menu,
they are not visible.

2015-09-30 2:46 GMT+02:00 Josh <notifications@github.com>:

**Comment by josh18** [comment]
It's not my plugin, it works fine for me. You need to change it to 4.4.0 not 4.3.0, you are missing all the icons added in 4.4.0.

**Comment by Liewebs** [comment]
Y es. I testes un 4.3.0 and i changed again yo 4.4.0 ando the problem OS
the  same.

**Comment by Liewebs** [comment]
The problem is the same...

**Comment by josh18** [comment]
Sorry but without a demo I can't help. It is definitely an issue with an older version of FontAwesome being loaded in though.

**Comment by Liewebs** [comment]
Let me some days to install a demo in my hosting and give you credentials
to test it and check it. I will inform you. Give me an
email address

**Comment by josh18** [comment]
joshhunt180@gmail.com

**Comment by josh18** [comment]
Do you ever get this fixed?

**Comment by Liewebs** [comment]
Hi,

No, I have not fixed yet. I hope this week to give you a credentials to
access into my demo shop and check the issue. I am working so hard and no
time enought some days ago...

I am in a project to build a tinymce module with full configuration and
features and I want to add your plugin in my project, but It is neccessary
fix this issue before.

Best regards!

Joaquín Bosch

2015-10-21 3:55 GMT+02:00 Josh <notifications@github.com>:

**Comment by criloz** [comment]
Hi I just fixed this adding this line to the  [fontawesome.min.css](https://github.com/josh18/TinyMCE-FontAwesome-Plugin/blob/master/fontawesome/css/fontawesome.min.css) file.

```css
@font-face {
     font-family: "FontAwesome";
      src: url(https://netdna.bootstrapcdn.com/font-awesome/4.4.0/fonts/fontawesome-webfont.ttf) format("truetype");
}
h1 { font-family: "FontAwesome", sans-serif }```

**Comment by josh18** [comment]
I'm not sure how that would change anything unless you are using an old version of FontAwesome?

**Comment by criloz** [comment]
using the version of your guide.  it force to load the font for the tinymce menu, previously it only was working on the text area.

**Comment by Liewebs** [comment]
Thanks. with this code added just fixed in my tinymce.
This bug was detected for more than one user, and reported to me...I think the problem is not from the users...
