### ISSUE TITLE
TinyMCE Menu not show  "\f024" and Etc.

### ISSUE THREAD

**Issue by bbfriend** [josh18/TinyMCE-FontAwesome-Plugin#19]
Sorry .. I still do not accustomed to github.
And I English is not a good

1:TinyMCE Menu not show  "\f024"
![tmc_fap01](https://cloud.githubusercontent.com/assets/14984349/10309880/f0fe4c4c-6c79-11e5-81f4-b573b50a9404.gif)
I add  "font-family: FontAwesome" to fontawesome.min.css
.mce-i-flag:before{content:"\f024";font-family: FontAwesome;}
 Appeared
![tmc_fap02](https://cloud.githubusercontent.com/assets/14984349/10310089/18adf08e-6c7b-11e5-9de3-ad7f4d8a9a11.gif)

2: Spinner not rotate　.. Not add fa-spin 
　Cause　：I had to translate the Spinner in langs/*.js .
　Don't　Change　’Spinner'.
   This Code  e+="Spinner"===x?　in plugin.min.js
3: Submission ja.js

tinymce.addI18n('ja', {
    'Icons': 'Icon',
    'Web Application': '一般',
    'File Type': 'ファイルタイプ',
    'Spinner': 'Spinner', /** Don't Change! Not rotate v1.6.0 **/
    'Form Control': 'Formコントロール',
    'Currency': '通貨',
    'Text Editor': 'エディタ',
    'Directional': '矢印・方向',
    'Video Player': 'プレイヤー',
    'Brand': 'ブランド',
    'Medical': '医療',
    'Transportation': '交通',
    'Gender': '性',
    'Payment': '支払い',
    'Chart': 'チャート',
    'Hand': '手'
});

**Comment by josh18** [comment]
1. Not sure what is causing this, maybe something in your css? Can you inspect the flag icon with your dev tools and see if there is any font assigned to .mce-i-flag::before?

2. You are right, this is a bug. I've fixed it and will update it once we have finished (1) and (3).

3. Thanks! I will add this in. Can you add the translation for Spinner? Also are these ok?
'Icons': 'Icon',
'Form Control': 'Formコントロール',

**Comment by bbfriend** [comment]
Thanks!
1. Now Check . 
   My TinyMCE's skins is lightgray..
        skin: "lightgray",
        toolbar_items_size: "small",
   I found,  overrided : tinymce/plugins/fontawesome/css/fontawesome.min.css -->
    /tinymce/skins/lightgray/skin.min.css
   .mce-btn-small .mce-ico { font-family: tinymce-small,Arial;}　

　　However, I thought better to override it is safe .mce-i-flag:before{     .... font-family: FontAwesome;}
 
2. Thanks!
3. I add translation for Spinner. New translation ja.js

tinymce.addI18n('ja', {
'Icons': 'Icon',
'Web Application': '一般',
'File Type': 'ファイルタイプ',
'Spinner': 'スピナー', 
'Form Control': 'Formコントロール',
'Currency': '通貨',
'Text Editor': 'エディタ',
'Directional': '矢印・方向',
'Video Player': 'プレイヤー',
'Brand': 'ブランド',
'Medical': '医療',
'Transportation': '交通',
'Gender': '性',
'Payment': '支払い',
'Chart': 'チャート',
'Hand': '手'
});

**Comment by josh18** [comment]
(1) Ah I see now, it doesn't work when you use small buttons. I will fix this.

(3) Thanks I'll add this in today.

Don't worry your English is pretty good and it just takes a little time to learn Github :D

**Comment by bbfriend** [comment]
My English is "Powerd by GoogleTranslate".. (^^;

**Comment by g7sim** [comment]
The mce-i-flag is in fontawesome.min.css .mce-i-flag {display: inline-block;font-family: "Font Awesome 5 Pro"; - so is fa-chevron-double-up - and many others are also PRO.
icons.yml are in the zip under metadata
