### ISSUE TITLE
Search/Filter icons like on FontAwesome website

### ISSUE THREAD

**Issue by msieb** [josh18/TinyMCE-FontAwesome-Plugin#22]
It would be nice to have a search/filter function for the FontAwesome plugin that returns the same or similar results as the filter feature on http://fortawesome.github.io/Font-Awesome/icons/. Maybe it is possible to also make use of https://github.com/algolia/algoliasearch-client-js

**Comment by josh18** [comment]
I agree, I'll probably get to this eventually but feel free to create a pull request if you want to implement it.

**Comment by josh18** [comment]
I've added search in v2.
