### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by seancodev** [josh18/TinyMCE-FontAwesome-Plugin#25]
Hello,

Doing this update prevents the unicode options from working from previous versions. Those people who have used the unicode versions from 1.7 or lower, will have to go back and update their content as the icons don't show up in the editor.

A quick fix for those using Unicode is attached.
[plugin.zip](https://github.com/josh18/TinyMCE-FontAwesome-Plugin/files/73934/plugin.zip)

Thanks.

**Comment by seancodev** [comment]
And here is the minified version (without the JS popup alert).
[plugin.zip](https://github.com/josh18/TinyMCE-FontAwesome-Plugin/files/73937/plugin.zip)

**Comment by josh18** [comment]
I've added a fix in v2.0.3, I think it should work but let me know if it doesn't.

**Comment by Liewebs** [comment]
Adding this file my issue was fixed. Please Josh check my issue ticket

**Comment by Liewebs** [comment]
but some icons, only some, are not visible.
