### ISSUE TITLE
Issues with Lists-Icons

### ISSUE THREAD

**Issue by theBear** [josh18/TinyMCE-FontAwesome-Plugin#26]
Hi, thank you for this very helpful plugin!

I use the [list-function of font awesome](https://fortawesome.github.io/Font-Awesome/examples/#list). It's quite nice to see inserting templates and pre-existing content with the Icons as List-Points. Unfortunately it's a bit buggy to edit those. 

1. You can delete existing lines only by using the backspace-key.

2. If you double-click the line and enter a text, it will delete the Icon.

3. To add a new line with the same icon above, you have to copy the line and paste it. Typing Enter/Return won't work. And even this work-around doesn't work proper.

**Comment by josh18** [comment]
How are you implementing the icons? Have you got an example that I can look at?

**Comment by theBear** [comment]
The code is not public, but it's like this simple snippet in the header:

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    
    <script>
    tinymce.init({
    selector: '#editor',
    plugins: "template code link lists fontawesome noneditable",
    menubar: false,
    toolbar: 'newdocument template | undo redo | link unlink | code',
    height: '200px',
    templates: [ {title: 'add list', description: 'adds a list', url: 'list.html'} ],
    cleanup : false,
    verify_html : false,
    statusbar: false,
    extended_valid_elements: 'span[class]',
    content_css: '//netdna.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css'
    });
    </script>

and this in the body:
    
        <textarea id="editor"></textarea>
    
...and the list.html contains just:
    
    <ul class="fa-ul">
    <li><i class="fa-li fa fa-caret-right"></i>XYZ</li>
    <li><i class="fa-li fa fa-caret-right"></i>XYZ</li>
    <li><i class="fa-li fa fa-caret-right"></i>XYZ</li>
    </ul>

I hope, this will help.

**Comment by Liewebs** [comment]
Hi,

I have installed your new version in TinyMCE last version and the fontawesome icons are not visible in the editor. I send you attachment screenshots.

I have configured correctly to content_css: '//netdna.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css'

you can see that css code is from css file of your plugin.
![sin titulo](https://cloud.githubusercontent.com/assets/14276490/12361136/9ef1f042-bbbc-11e5-8971-22c71672aa4a.jpg)

**Comment by theBear** [comment]
@Liewebs May you please post this somewhere else? This problem has nothing to do with mine.

**Comment by Liewebs** [comment]
ops, Sorry..

**Comment by josh18** [comment]
Sorry been busy the last couple of days.

1. How else would you delete a line?
2. Can't seem to reproduce this.
3. Yeah this is expected, in TinyMCE a fontawesome icon is essentially just treated as another character so there is no logic for it to copy and icon to the next row.

Regardless IMO the best way for you to do something like this would be to add the icon via css. You could use something like:

```css
.custom-list li::before {
    content: "\f0da";
    display: inline-block;
    font: normal normal normal 14px/1 FontAwesome;
    font-size: inherit;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```

**Comment by theBear** [comment]
Thanks for the reply and that you try to help me! Is this CSS related to your plugin? Or to TinyMCE? Or my general Theme? And where and how I have to add it? 

...or is it an alternative to `<li><i class="fa-li fa fa-caret-right"></i>XYZ</li>`?

**Comment by josh18** [comment]
It is an alternative (most likely a better one). You would need to add it in to TinyMCE as well as your theme I would assume. You should be able to use the [content_css](https://www.tinymce.com/docs/configure/content-appearance/#content_css) option to add it to TinyMCE. So your html would just look something like:
```html
<ul class="custom-list">
    <li>A</li>
    <li>B</li>
    <li>C</li>
</ul>
```
(might need to add some additional css for padding / margin / removing the original dot).

Let me know how you go.

**Comment by theBear** [comment]
Thank you!

I think, the `class="custom-list"` could be a problem, because if you enter a new unordered list in TinyMCE it has no class in the `<ul>`-tag by default. So you can prevent the icon-issue, but it is no final solution. Or am I wrong? O.o

**Comment by josh18** [comment]
Well how did you plan on getting `class="fa-ul"` into TinyMCE?

You could just have it on `<ul>`. Or you can add it to the html via TinyMCE custom formats.

**Comment by theBear** [comment]
As mentioned [here](https://github.com/josh18/TinyMCE-FontAwesome-Plugin/issues/26#issuecomment-171395330) I'm using the official template-plugin to insert an example-list with the right classes and bad problems. 

Thanks for the hints. I will check it this week :-)

**Comment by theBear** [comment]
I think I see the solution. Actually there is no need to use font-awesome anyway in TinyMCS. In the editor there are the normal unordered list-points. And to the div, the content will appear later, I add the custom-css like you mentioned before.
