### ISSUE TITLE
Icons are not visible in TinyMCE editor Prestashop

### ISSUE THREAD

**Issue by Liewebs** [josh18/TinyMCE-FontAwesome-Plugin#27]
Hi Josh18
![fontawesome](https://cloud.githubusercontent.com/assets/14276490/12361245/4f468908-bbbd-11e5-98e7-1067a6306965.jpg)
,

I have installed your new version in TinyMCE last version and the fontawesome icons are not visible in the editor. I send you attachment screenshots.

I have configured correctly to content_css: '//netdna.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css'

you can see that css code is from css file of your plugin.

I don't know what is the reason for this issue. I have tested and checking all parameters but I don't find the fix.

**Comment by josh18** [comment]
Sorry I've been busy the last couple of days. Did you get this fixed? If not do you have a demo I can look at?

It looks like the html is correct so the issue must be with the css. I'm guessing for whatever reason the Font Awesome css file isn't loading. Is there any error messages in the dev console? Does it work in any other browsers?

**Comment by Liewebs** [comment]
Hi,

I have fixed parcially with the fix provided with anohter user:

https://github.com/josh18/TinyMCE-FontAwesome-Plugin/issues/25

But some icons are still disspeared. You can test it in my demo shop:

http://www.liewebs.com/demo-shop/admin-demo/

User: demo@demo.es
Pass: demodemo

Go to "MODULES" and then "configure". At the footer of this section you can find the TinyMCE editor.

**Comment by josh18** [comment]
Pretty sure it is caused by FontAwesome 4.4.0 being requested in this file: http://www.liewebs.com/demo-shop/js/tiny_mce/plugins/fontawesome/css/fontawesome.min.css.

Can you remove that and see what happens?

**Comment by Liewebs** [comment]
Hi, 

If I remove this line more icons are not visible than If I let intact this line.

In fact I created this line to be able to see the icons correctly.

Please see screenshot.
![screenshot](https://cloud.githubusercontent.com/assets/14276490/12530714/c289c652-c1e7-11e5-8058-8b0713e925d8.jpg)

**Comment by Liewebs** [comment]
But I just fixed replacing this line for the following:

@font-face {font-family: "FontAwesome";src: url(https://netdna.bootstrapcdn.com/font-awesome/4.5.0/fonts/fontawesome-webfont.ttf) format("truetype");}

**Comment by josh18** [comment]
Oh yeah I think this is a fix just for you because PrestaShop loads in an old version of FontAwesome so this overwrites it.

**Comment by Liewebs** [comment]
Maybe, because Prestashop loads the fontawesome version of each tinyMCE skins, and It overwrites it. I hope It is useful for all Prestashop users.

Best regards and thank you for your great plugin.!

**Comment by hombean** [comment]
Could you enclose here full corrected version of the plugin for Prestashop? I tried add @font-face {font-family: "FontAwesome";src: url(https://netdna.bootstrapcdn.com/font-awesome/4.5.0/fonts/fontawesome-webfont.ttf) format("truetype");}
to \js\tiny_mce\plugins\fontawesome\css\fontawesome.min.css
but nothing is changed!
Dialog window for choosing an icon is empty like on first screenshot. I am using v2.0.6 of plugin and Prestashop 1.6.1.5.

**Comment by josh18** [comment]
@hombean got a demo I can look at? Note that `4.5.0` -> `4.6.3` (my instructions were slightly out of date)

**Comment by hombean** [comment]
Unfortunately my project is on local server. But I'll give you more information for problem with the plugin and Prestashop 1.6.1.5:
1. If I use plugin.min.js from your plugin v2.0.6 no icon seen in dialog window, just empty spoilers with labels of icon's categories.
2. If I use plugin.min.js from anohter user: [#25](https://github.com/josh18/TinyMCE-FontAwesome-Plugin/issues/25) I can see icons in dialog window. But some icons presented as squares. Choosing them insert right icons in tinyMCE window and are correctly shown on site too.

Squares are replaced by right icons  if adding:

@font-face {font-family: "FontAwesome";src: url(https://netdna.bootstrapcdn.com/font-awesome/4.6.3/fonts/fontawesome-webfont.ttf) format("truetype");}
 
at the beginning of file: \js\tiny_mce\plugins\fontawesome\css\fontawesome.min.css

Thank for that fix, Liewebs! And you are correct josh18, I replace in that line 4.5.0 to 4.6.3. 

3. But there are still 2 bugs:

One was mentioned here: At first opening dialog window first category **Web Application** do not open fully. I can see just 2 rows of icons. But if you choose any other category, for example, **File Type** and once again **Web Application**, it opens now fully.

Second bug: Search of icons does not working. While searching any text alll categories fully opened, but now filtered icons.

I am using tinyMCE 4.3.12, Prestashop v1.6.1.5 and fontawesome plugin v2.0.6.
Fontawesome v4.6.3. All testing is done on local server Open Server.

**Comment by hombean** [comment]
Here screenshots of bugs. No icons with your default plugin.min.js:
![no_icons_in_dialog](https://cloud.githubusercontent.com/assets/3042210/15561053/c596aa1c-22fa-11e6-8d59-062cc3cf9bf3.jpg)

**Comment by hombean** [comment]
Icons are now shown with enclosed file (but I am not programmer and the
[plugin.min.zip](https://github.com/josh18/TinyMCE-FontAwesome-Plugin/files/283282/plugin.min.zip)
![first opening](https://cloud.githubusercontent.com/assets/3042210/15561103/2aafc26c-22fb-11e6-84da-44b8574eae89.jpg)

Icons now are seen in dialog window, but you can see another bug: at first opening of dialog windows first category do not open fully.

re may be hidden errors):

**Comment by hombean** [comment]
Second bug with squares  in dialog window: 
![squares](https://cloud.githubusercontent.com/assets/3042210/15561140/7a69befc-22fb-11e6-94e2-6de1d10793bd.jpg)

was corrected by replacing your default fontawesome.min.css by this: 
[fontawesome.min.zip](https://github.com/josh18/TinyMCE-FontAwesome-Plugin/files/283284/fontawesome.min.zip)

**Comment by josh18** [comment]
That's really weird it works fine for me 😕 . If I have time I will download PrestaShop and test, I think it is the cause of all the issues.

**Comment by hombean** [comment]
Last bug with not working search. No filtered icons:
![search](https://cloud.githubusercontent.com/assets/3042210/15561205/f02b73ce-22fb-11e6-8248-a3f90bd223ae.jpg)
