### ISSUE TITLE
Breaks tinymce in IE11?

### ISSUE THREAD

**Issue by chellisa** [josh18/TinyMCE-FontAwesome-Plugin#30]
Hello, 
I use your wonderful plugin together with tinymce 4.3.8. and it works fine in firefox or google chome. But the plugin unfortunately seems to break the tinymce in Internet Explorer 11.

I always get the error: "Unable to get property 'innerHTML' of undefined or null reference", (File: plugin.min.js, Line: 3, Column: 14984)

See in my screenshot: Neither the toolbar-button is displayed, nor the icons within the icon select window. The second textarea on the page (below "Feld 2") isn't shown at all.

![bildschirmfoto 2016-04-05 um 15 46 51](https://cloud.githubusercontent.com/assets/2699092/14283970/c071b694-fb45-11e5-91de-28cfcd40e4c9.png)

Tinymce works fine if I do not include fontawesome plugin in IE11. 

Can you help?

**Comment by josh18** [comment]
Should be fixed now, let me know if it isn't working.
