### ISSUE TITLE
SyntaxError: missing ; before statement

### ISSUE THREAD

**Issue by webdev20** [josh18/TinyMCE-FontAwesome-Plugin#34]
Get this error after adding the plugin:
`SyntaxError: missing ; before statement`
`unicode:"f205",created:4.2,categories:["Web Application Icons"]},{name:"Bicycle"...`

I use tinymce 4.3.11

**Comment by josh18** [comment]
What browser? I'll try to do some testing today.

**Comment by josh18** [comment]
Sorry it should be fixed now, I think I failed copy / paste or something. It was just the min file that was broken.
