### ISSUE TITLE
using the icons

### ISSUE THREAD

**Issue by swimd** [josh18/TinyMCE-FontAwesome-Plugin#35]
When using the icons in tiny mice, if the first thing you enter is a Icon, after pressing "Enter", everytime you press enter the icon display again on each new line. And they cannot be deleted. When looking at the source code, they don't even actually exist. 

The only way to add icon without it creating another one on each line is to put a space first, then inputting the icon. 

I have made a video showing this, it wouldnt let me upload the zip here for somereason so it is at this link  http://swimd.com/iconerrorvideo.zip

**Comment by josh18** [comment]
Hmm can't reproduce. Are you using the latest versions of TinyMCE and my plugin? Also what browser are you using?
