### ISSUE TITLE
Feature Request: Aria Labels

### ISSUE THREAD

**Issue by walker233** [josh18/TinyMCE-FontAwesome-Plugin#36]
Please consider adding aria-labels for the icons, and some meaningful ways for the individuals to know which label is being applied for the specific icon, when more than one name is available for the icon.

**Comment by josh18** [comment]
Sorry probably not going to happen, I've thought about doing it but it is too complicated. I think the only way that it could work is if users manually entered the label each time because one icon can have so many different meanings. Feel free to make a pull request though.
