### ISSUE TITLE
invisible icons in the editor field

### ISSUE THREAD

**Issue by moraks** [josh18/TinyMCE-FontAwesome-Plugin#37]
I put icons, their code is inserted, but can not see them in the editor field. 
How can I make them visible? (i am use joomla 3.6)
See screenshot (click to full size): 
1. Icon in menu  visible normal:
 <a target="_blank" href="http://s018.radikal.ru/i511/1607/be/34a8e85c1a26.jpg"><img src="http://s018.radikal.ru/i511/1607/be/34a8e85c1a26t.jpg" ></a>
2. Editor enable (icon invisible)
<a target="_blank" href="http://s009.radikal.ru/i307/1607/ea/4f4143b7ac28.jpg"><img src="http://s009.radikal.ru/i307/1607/ea/4f4143b7ac28t.jpg" ></a>
3. Editor disable
<a target="_blank" href="http://s019.radikal.ru/i635/1607/d7/4eed40c16333.jpg"><img src="http://s019.radikal.ru/i635/1607/d7/4eed40c16333t.jpg" ></a>

**Comment by josh18** [comment]
Do you have FontAwesome running on that page?

**Comment by josh18** [comment]
I assume you have added this bit into `tinymce.init()`?
```
content_css: '//netdna.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css';
```
Though even if the font hadn't loaded it should show an empty box character. If you have a demo I can take a look.

**Comment by moraks** [comment]
I don't know add tinymce.init()...  tinymce at joomla - JS script. Conact me at whatsApp  (+79231687361) I'm send you login/pass of my site.

**Comment by josh18** [comment]
I am pretty sure that is the issue. I don't use Joomla but you just need to find a place to add that in. Where did you add this `plugins: 'fontawesome noneditable'`?

**Comment by moraks** [comment]
I don't add plugin  'fontawesome noneditable' I am connect TinyMCE-FontAwesome-Plugin
  in advanced settings of  TinyMCE Plugins - I wrote  'fontawesome' in line [custom plugins].  It work, but only at TinyMCE tools menu.

**Comment by josh18** [comment]
Maybe you can add it under Custom CSS Classes? I don't use Joomla so I don't really know, [here is a list of options] or maybe you could try asking a Joomla forum.

Anyways this is the info that you need to make sure is in there otherwise it won't work:
```js
tinymce.init({
    ...
    plugins: 'fontawesome noneditable'
    ...
    extended_valid_elements: 'span[class]'
    ...
    content_css: '//netdna.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css';
    ...
    toolbar: 'fontawesome';
    ...
});
```

**Comment by moraks** [comment]
Installation TinyMCE-FontAwesome-Plugin on Jooma/
1.	Copy folder “fontawesome” from archive TinyMCE-FontAwesome-Plugin-master.zip to [HOME_DIR]:/media/editors/tinymce/plugins/
2.	Go to joomla admin panel Choose at main menu “Extensions”>” Plugins”, search “Editor - TinyMCE”, open it config, to field “Valid Elements” add this (+a[*],+i[*],+em[*],+li[*],+span[*],+div[*]) without()! 
3.	To field “Custom CSS Classes” add: (http://netdna.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css) without() prefix “http://” is important.
4.	Go to “Advanced” tab and to field “Custom Plugin” add (fontawesome) without() too.
5.	Save plugins config.

**Comment by moraks** [comment]
Update: 
1) With new joomla and TinyMCE Icon in menu invisible:
To fix this: add line 
`@import url('https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'); i.mce-ico.mce-i-flag {font-family: fontawesome !important;}` 
TO fontawesome.min.css in [HOME_DIR]:\media\editors\tinymce\plugins\fontawesome\css\
(after install plugin)
2) Go to joomla admin panel Choose at main menu “Extensions”>” Plugins”, search “Editor - TinyMCE”, open it config, tap on [set 0] tab and to field “Valid Elements” add this : *[*]
