### ISSUE TITLE
TinyMCE removes classes from span element

### ISSUE THREAD

**Issue by FilipQL** [josh18/TinyMCE-FontAwesome-Plugin#40]
Hi,

When I choose some Font Awesome icon, TinyMCE removes classes from span element. For example, if I want to add:

`<span class="fa fa-university"></span> `

at the end I will have just:

`<span></span> `

Also, in source code editor I tried to add `<i class="fa fa-university"></i>` but the problem is same - classes are deleted by TinyMCE (`<i></i>`).

I am using TinyMCE v4.4.1 and these are my settings:

```
        tinymce.init({
            selector: '#body',
            height: 500,
            theme: 'modern',
            plugins: [
                'advlist autolink lists link image charmap preview hr anchor pagebreak',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons template paste textcolor colorpicker textpattern codesample fontawesome noneditable'
            ],
            toolbar1: 'insertfile undo redo | formatselect fontselect fontsizeselect fontawesome',
            toolbar2: 'bold italic underline strikethrough forecolor backcolor removeformat superscript subscript | alignleft aligncenter alignright alignjustify | outdent indent',
            toolbar3: 'code preview | link unlink anchor image media | codesample | bullist numlist table blockquote hr nonbreaking | charmap emoticons | visualchars visualblocks',
            image_advtab: true,
            relative_urls: false,
            extended_valid_elements: 'span',
            content_css: '/css/all.css' // this includes fontwawesome...
        });
```

**Comment by FilipQL** [comment]
Ok, instead of:

`extended_valid_elements: 'span',`

it should be:

`extended_valid_elements: 'span[class]',`

And now it works.

**Comment by josh18** [comment]
As far as I can tell `extended_valid_elements` isn't necessary at all? Testing on v4.6.3.

**Comment by FilipQL** [comment]
@josh18 Hmm, I am using Font Awesome v4.6.3 and TinyMCE 4.4.1. ... and if I don't have `extended_valid_elements` or `valid_elements: "*[*]"` - classes are deleted.

**Comment by josh18** [comment]
Oh whoops I was getting TinyMCE version mixed up with FontAwesome. This is my demo: https://gist.github.com/josh18/0528af08b659bbd46d05d2ffd4a05303

Does it work ok for you?

**Comment by FilipQL** [comment]
@josh18  Your plugin works great! It seems that this issue with removing classes of span element is more related to TinyMCE than this plugin. I have one question - once you add some icon - can you change the size of it (change font size of icon **after** it was added)?

**Comment by josh18** [comment]
So are classes still deleted even if you don't use `extended_valid_elements` or `valid_elements`? I'm just trying to narrow it down just in case it doesn't work for other people.

The icon font size should match the font-size of the text. If you want to make it bigger or smaller than the existing I would recommend either use css on the `.fa` class or wrap the icon in a new `<span>` with the required styles.

**Comment by FilipQL** [comment]
@josh18 Now I removed `valid_elements: "*[*]"` (also, there is no `extended_valid_elements`) and it works fine. FFS, I was sure that it didn't work well (classes of span elements were deleted in that case). Don't know what to say, sorry for wasting your time.

**Comment by josh18** [comment]
Lol no worries 😄 .
