### ISSUE TITLE
Unable to change font-size and color of the inserted font-awsome icon

### ISSUE THREAD

**Issue by antonStezhkin** [josh18/TinyMCE-FontAwesome-Plugin#41]
I can not change font-size and color of the inserted icon. 
I'm using TinyMCE v 4.4.1.
The demo is [here](http://test9.must.by/bug_issue/index.htm)

**Comment by josh18** [comment]
Unfortunately this isn't really possible due to the necessary `mceNonEditable` class. Some possible options:

1. Edit the color plugin so that it removes `mceNonEditable` before modification and then adds it back in again afterwords.

2. Use style formats, something like this:
```js
tinymce.init({
    style_formats: [
        {title: 'Color', items: [
			{title: 'Red', block: 'p', styles: {'color': '#f00'}},
			{title: 'Green', block: 'p', styles: {'color': '#0f0'}},
			{title: 'Blue', block: 'p', styles: {'color': '#00f'}}
		]},
    ]
});
```
