### ISSUE TITLE
Problem with special characters

### ISSUE THREAD

**Issue by huubl** [josh18/TinyMCE-FontAwesome-Plugin#42]
The plugin converts special characters in the source code option in TinyMCE. How to prevent this?

Example:
`&eacute;` is converted to é in the source code. 
https://fiddle.jshell.net/huubl/8kwxcr2t/

**Comment by josh18** [comment]
It is caused by [these lines](https://github.com/josh18/TinyMCE-FontAwesome-Plugin/blob/master/plugin.js#L324-L338).

The issue is if you `innerHTML` it gives you the converted html. Can you think of a better way to make the modifications? Maybe regex I guess but it doesn't seem very nice... Maybe TinyMCE has some built in way?

**Comment by huubl** [comment]
I removed [all these lines](https://github.com/josh18/TinyMCE-FontAwesome-Plugin/blob/master/plugin.js#L323-L355) and added this to tinymce.init:

```
tinymce.init({
    ...
    valid_elements: "span[*]",
    noneditable_noneditable_class: "fa"
});
```
To prevent TinyMce from removing the empty span tags and make the .fa classes noneditable. It seems to work and keeps the source unconverted. What do you think?

**Comment by josh18** [comment]
Looks good to me!

**Comment by josh18** [comment]
When I was testing I thought I found a bug where TinyMCE wasn't treating the icon like a separate character but I wasn't sure how it happened and I couldn't seem to reproduce it. Let me know if you notice it though.

**Comment by huubl** [comment]
I'm not sure, but I think we need to use: _**extended**_valid_elements: 'span[*]'_ instead of _valid_elements: "span[*]"_. To add it to the existing rules. Have a look [at this](https://www.tinymce.com/docs/configure/content-filtering/#extended_valid_elements).

**Comment by josh18** [comment]
Yeah that seems right, I've updated the readme now.
