### ISSUE TITLE
When inserting an icon as the very first element in the editable field, it does not show up

### ISSUE THREAD

**Issue by tonimichel** [josh18/TinyMCE-FontAwesome-Plugin#43]
I experience this issue in inline mode and non-inline mode. However when the the textbox has at least one character (even a whitespace), it works fine.

**Comment by josh18** [comment]
I think this is a bug with TinyMCE so I've made an issue there: https://github.com/tinymce/tinymce/issues/3175

If you do need it to work urgently 2.0.7 should work.

**Comment by TomCorvus** [comment]
You can try something :

Modify plugin.js file like this:
From:
` function i() {
            var b = this.getAttribute("data-id");
            this.hasAttribute("data-spin") && (b += " fa-spin"), a.execCommand("mceInsertContent", !1, '<span class="fa fa-' + b + '"></span>'), f.close()
        }`
To:
`    function i() {
            var b = this.getAttribute("data-id");
            this.hasAttribute("data-spin") && (b += " fa-spin"), a.execCommand("mceInsertContent", !1, '&thinsp;<span class="fa fa-' + b + '"></span>&nbsp;'), f.close()
        }`

It's just a little fix to wait TinyMCE update.

**Comment by josh18** [comment]
^ is a good fix if it's causing issues for you. However it does add extra characters in so I won't include it inside the plugin at the moment.

TBH it doesn't look like TinyMCE is going to fix it anytime soon so someone might have to make a pull request. I'll do it if I find some free time but it probably won't be for a while.

**Comment by cmb69** [comment]
FWIW: the best workaround I'm able to come up so far, would be to check whether `editor.selection.getNode().textContent === ""`, and to append a `&nbsp;` only in this case.

**Comment by josh18** [comment]
I would be happy to accept a pull request as I don't really plan on working on this anytime soon and it seems that the TinyMCE bug isn't going to be fixed.
