### ISSUE TITLE
icon doesn't appear in editor

### ISSUE THREAD

**Issue by t-bru** [josh18/TinyMCE-FontAwesome-Plugin#47]
This may not be an issue but rather a config error on my part, but the font awesome icon doesn't appear in the editor when i select it.  When i view the text outside of the editor the icon is displayed.  DO you know what could be causing this?  Thanks

**Comment by josh18** [comment]
Have you added this line to your TinyMCE config?
```js
content_css: 'https://netdna.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css'
```

**Comment by t-bru** [comment]
I added that line but pointed to font awesome inside my library first i tried the path to the font aewsome lib that i copied to the tinymce plugin folder then i tried the path to font awesome inside my library folder.

**Comment by t-bru** [comment]
here is my config in case you need to see what I'm doing 
tinymceConfig = {
    	  selector: "textarea",
    	  height: 300,
    	  removed_menuitems: 'newdocument',
          content_css: 'http://mysite/library/font-awesome/4.6.2/css/font-awesome.min.css',
          noneditable_noneditable_class: 'fa',
          extended_valid_elements: 'p[*]',
    	  default_link_target: "_blank",
    	  plugins: [
    	    'lists link charmap anchor',
            'fontawesome noneditable',
    	    'searchreplace visualblocks',
    	    'table paste autolink '
    	  ],
    	  target_list: [
    	                {title: 'None', value: ''},
    	                {title: 'Same page', value: '_`self'},
    	                {title: 'New page', value: '_blank'}
    	            ],
    	  
    	  toolbar: 'fontawesome | externalLink undo redo | styleselect | bold italic fontselect | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent image',
    	  setup: function (editor) {
    	        editor.on('change', function () {
    	            editor.save();
    	        });    	        
    	  },
    	  theme_advanced_fonts : 'Andale Mono=andale mono,times;'+
          'Arial=arial,helvetica,sans-serif;'+
          'Arial Black=arial black,avant garde;'+
          'Book Antiqua=book antiqua,palatino;'+
          'Comic Sans MS=comic sans ms,sans-serif;'+
          'Courier New=courier new,courier;'+
          'Georgia=georgia,palatino;'+
          'Helvetica=helvetica;'+
          'Impact=impact,chicago;'+
          'Symbol=symbol;'+
          'Tahoma=tahoma,arial,helvetica,sans-serif;'+
          'Terminal=terminal,monaco;'+
          'Times New Roman=times new roman,times;'+
          'Trebuchet MS=trebuchet ms,geneva;'+
          'Verdana=verdana,geneva;'+
          'Webdings=webdings;'+
          'Wingdings=wingdings,zapf dingbats'
    	};

**Comment by t-bru** [comment]
it's working now!  I'm not sure if something was cached but I messed with the config and went' back to original and now it works.  Great plugin btw!

**Comment by josh18** [comment]
Glad you got it working!
