### ISSUE TITLE
Activating the plugin disables the editor

### ISSUE THREAD

**Issue by Trigone** [josh18/TinyMCE-FontAwesome-Plugin#49]
Hi.
I followed your instructions: copying the fontawesome folder in the tinymce plugins folder, then copying the code you provide in the tinymce JS init file.
But when I do this, the field where the tinymce editor is supposed to display is totally desactivated. I cannot type any data in it: there's no editor and no field any more!

In fact, as soon as I add "fontawesome" in the "plugins: '...'" line of the JS config file, it deactivates the editor. So it doesn't come from any syntax error in the init file.

Note: I use tinymce in an Xcrud PHP script, not WordPress or Joomla.
Any hint?
Thanks.
Regards

**Comment by josh18** [comment]
Have you got a demo that I can look at? Are there any errors in the developer console?

**Comment by josh18** [comment]
Closing as no response.
