### ISSUE TITLE
No conversion on submit

### ISSUE THREAD

**Issue by Cyboulette** [josh18/TinyMCE-FontAwesome-Plugin#7]
Hi,

I use your plugin with tinymce 4.X and fontawesome 4, its work fine when i use it in the tinymce editor, but when i submit the conversion doesn't do any effect.
In editor : http://puu.sh/ebUSV/3cd60c2efd.png
When i submit : http://puu.sh/ebUWb/2b457fda6e.png

Font-awesome is loaded on the website page's.

Sorry for my bad english, if you want more information, please contact me.

**Comment by josh18** [comment]
Where is the content being stored? If it is being stored in a mysql database you need to make sure that the column is set to utf8.

**Comment by Cyboulette** [comment]
Thank's, it's now OK.
But i have do my own plugin for use <i class="fa fa-ID"></i> instead of the unicode char ;)
