### ISSUE TITLE
Some icons like squares in the popup

### ISSUE THREAD

**Issue by scrakcho** [josh18/TinyMCE-FontAwesome-Plugin#8]
Some icons in the popup appear a square like if original fontawesome wasn't loaded
![fontawesome](https://cloud.githubusercontent.com/assets/6636661/6751593/00916d9a-cf06-11e4-9f65-51841d42270e.png)

**Comment by josh18** [comment]
Sorry I think the readme was wrong, make sure you have `content_css: '//netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css';` (4.3.0 instead of 4.1.0)

**Comment by scrakcho** [comment]
Of course I already have updated the version :)

The error is still there. I have noticed that if I click in a square in the popup it appears right in the main text editor.

**Comment by josh18** [comment]
Not sure sorry, it seems to work for me. Are you sure you don't have another version of FontAwesome running on the page?

**Comment by scrakcho** [comment]
Fixed, the problem was loading two different versions of fontawesome
